### ISSUE TITLE
How to connect to an MQTT server also running in a docker container

### ISSUE THREAD

**Issue by vielmetti** [dceejay/nrdock#1]
Thanks for this effort, much appreciated. I don't know if issues go here or to the main Node-RED issues, but since this is specific to that, I thought I'd put it here.

I have Node-RED running under Docker on Ubuntu on AWS. The thought is that I'd run a second Docker on the same instance to bring up Mosquitto as an MQTT broker (in particular lapax/tiny-mosquitto) and make that a unit of computation. I did that, but now I'm puzzled as to the right way to get everything started so that it all runs at once.

**Comment by vielmetti** [comment]
Specifically here is output of `docker ps`

```
CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS              PORTS                    NAMES
40c09147eda1        lapax/tiny-mosquitto:latest   "/usr/sbin/mosquitto   12 minutes ago      Up 12 minutes       0.0.0.0:1883->1883/tcp   compassionate_bardeen   
76fe32fb83f7        theceejay/nreddock:latest     "npm start"            22 minutes ago      Up 22 minutes       0.0.0.0:1880->1880/tcp   boring_einstein      
```

**Comment by dceejay** [comment]
Hi Ed, err what is the issue ? they look like they are running ok ? Does this help - https://docs.docker.com/userguide/dockerlinks/

**Comment by vielmetti** [comment]
Yeah, I am just confused by docker still.

I want the nreddock container to talk to the tiny-mosquitto container (on the MQTT port), and I want to have a browser window open for the nreddock system, and I probably also want the MQTT docker to talk to other MQTTs somewhere else. Oh, and this should all be on a Raspberry Pi and it should launch at boot time and if Node-RED crashes for some reason it should restart.

I know that's all possible, and I just need to puzzle it out a piece at a time and sort through what's connect to what, and as always working examples help. In particular I have to wonder whether Node-RED and Mosquitto shoudl run in the same container.

**Comment by dceejay** [comment]
Well it would be "easier" if they did - but the on-trend micro-services bleeding-edge way would be to fragment as much as possible... :-)

**Comment by vielmetti** [comment]
Yeah, microservices is I think a reflection of widespread use of AWS. I really want microsystems, not microservices, I think....

**Comment by dceejay** [comment]
I have added a section to the README.md on Linking Containers - https://github.com/dceejay/nrdock/blob/master/README.md#linking-containers
